In [1]:
# the following script returns all the rows but only the first two
# columns.
import numpy as np
row1 = [10,12,13]
row2 = [45,32,16]
row3 = [45,32,16]
nums_2d = np.array([row1, row2, row3])
print(nums_2d[:,:2])


[[10 12]
 [45 32]
 [45 32]]


In [2]:
# Let’s see another example of slicing. Here, we will slice the rows from row
# one to the end of rows and column one to the end of columns. (Remember,
# row and column numbers start from 0.) In the output, you will see the last
# two rows and the last two columns.

row1 = [10,12,13]
row2 = [45,32,16]
row3 = [45,32,16]
nums_2d = np.array([row1, row2, row3])
print(nums_2d[1:,1:])


[[32 16]
 [32 16]]


In [3]:
# Broadcasting allows you to perform various operations between NumPy
# arrays of different shapes. This is best explained with the help of an example.
# In the script below, you define two arrays: a one-dimensional array of three
# items and another scaler array that contains only one item. Next, the two
# arrays are added. Finally, in the output, you will see that the scaler value, i.e.,
# 10 is added to all the items in the array that contains three items. This is an
# amazing ability and is extremely useful in many scenarios, such as machine
# learning and artificial neural networks.

array1 = np.array ([14,25,31])
array2 = np.array([10])
result = array1 + array2
print(result)

[24 35 41]


In [4]:
# Let’s see another example of broadcasting. In the script below, you add a
# two-dimensional array with three rows and four columns to a scaler array
# with one item. In the output, you will see that the scaler value, i.e., 10, will be
# added to all the 12 items in the first array, which contains three rows and four
# columns.

array1 = np.random.randint(1,20, size = (3,4))
print(array1)
array2 = np.array([10])
print("after broadcasting")
result = array1 + array2
print(result)

[[17  9  6 18]
 [19 13 11  9]
 [ 4 18  6 11]]
after broadcasting
[[27 19 16 28]
 [29 23 21 19]
 [14 28 16 21]]


In [5]:
# You can also use broadcasting to perform operations between twodimensional
# and one-dimensional arrays.
# For example, the following script creates two arrays: a two-dimensional array
# of three rows and four columns and a one-dimensional array of one row and
# four columns. If you perform addition between these two rows, you will see
# that the values in a one-dimensional array will be added to the corresponding
# columns’ values in all the rows in the two-dimensional array.
# For instance, the first row in the two-dimensional array contains values 4, 6,
# 1, and 2. When you add the one-dimensional array with values 5, 10, 20, and
# 25 to it, the first row of the two-dimensional array becomes 9, 16, 21, and 27.

array1 = np.random.randint(1,20, size = (3,4))
print(array1)
array2 = np.array([5,10,20,25])
print("after broadcasting")
result = array1 + array2
print(result)

[[18  7 17 13]
 [14  7  9 17]
 [19 19 18 15]]
after broadcasting
[[23 17 37 38]
 [19 17 29 42]
 [24 29 38 40]]


In [6]:
# Finally, let’s see an example where an array with three rows and one column
# is added to another array with three rows and four columns. Since, in this
# case, the values of row match, therefore, in the output, for each column in the
# two-dimensional array, the values from the one- dimensional array are added
# row-wise. For instance, the first column in the two-dimensional array
# contains the values 10, 19, and 11. When you add the one-dimensional array
# (5, 10, 20) to it, the new column value becomes 15, 29, and 31.

array1 = np.random.randint(1,20, size = (3,4))
print(array1)
array2 = np.array([[5],[10],[20]])
print("after broadcasting")
result = array1 + array2
print(result)


[[10 15  1  4]
 [ 8  5 17  7]
 [16  2  9 16]]
after broadcasting
[[15 20  6  9]
 [18 15 27 17]
 [36 22 29 36]]


In [7]:
# There are two main ways to copy an array in NumPy. You can either copy
# the contents of the original array, or you can copy the reference to the
# original array into another array.
# To copy the contents of the original array into a new array, you can call the
# copy() function on the original array. Now, if you modify the contents of the
# new array, the contents of the original array are not modified.
# For instance, in the script below, in the copied array2, the item at index 1 is
# updated. However, when you print the original array, you see that the index
# one for the original array is not modified.

array1 = np.array([10,12,14,16,18,20])
array2 = array1.copy()
array2[1] = 20
print(array1)
print(array2)

[10 12 14 16 18 20]
[10 20 14 16 18 20]
