In [1]:
# To load a NumPy array in the “NPY” format, you can use the load() method,
# as shown in the following example.
import numpy as np
a = np.array(([i + j for i in range(5)
for j in range(5)]))
# a is printed.
print("a is:")
print(a)
np.save('file', a)
print("the array is saved in the file.npy")
# the array is saved in the file.npy
b = np.load('file.npy')
# the array is loaded into b
print("b is:")
print(b)
# b is printed from file.npy
print("b is printed from file.npy")

a is:
[0 1 2 3 4 1 2 3 4 5 2 3 4 5 6 3 4 5 6 7 4 5 6 7 8]
the array is saved in the file.npy
b is:
[0 1 2 3 4 1 2 3 4 5 2 3 4 5 6 3 4 5 6 7 4 5 6 7 8]
b is printed from file.npy


In [2]:
# NumPy arrays contain various functionalities for performing statistical
# operations, such as finding the mean, median, and standard deviations of
# items in a NumPy array.
# To find the mean or average of all the items in a NumPy array, you need to
#pass the array to the mean() method of the NumPy module. Here is an
# example:

my_array = np.array([2,4,8,10,12])
print(my_array)
print("mean:")
print(np.mean(my_array))

[ 2  4  8 10 12]
mean:
7.2


In [3]:
# You can also find the mean in a two-dimensional NumPy array across rows
# and columns. To find the mean across columns, you need to pass 1 as the
# value for the axis parameter of the mean method. Similarly, to find the mean
# across rows, you need to pass 0 as the parameter value.
# The following script finds the mean of a two-dimensional array containing
# two rows and three columns across rows and columns.

my_array = np.random.randint(1,20, size = (2,3))
print(my_array)
print("mean:")
print(np.mean(my_array, axis = 1))
print(np.mean(my_array, axis = 0))


[[18 10  7]
 [ 1 10  9]]
mean:
[11.66666667  6.66666667]
[ 9.5 10.   8. ]


In [4]:
# The median() method from the NumPy module is used to find the median
# value in a NumPy array. Here is an example.

my_array = np.array([2,4,8,10,12])
print(my_array)
print("median:")
print(np.median(my_array))

[ 2  4  8 10 12]
median:
8.0


In [5]:
# Similarly, to find the median values across columns and rows in a twodimensional
# array, you need to pass 1 and 0, respectively, as the values for
# the axis attribute of the median method.
# The following script finds the median values across rows and columns for a
# two-dimensional array with three rows and five columns.

my_array = np.random.randint(1,20, size = (3,5))
print(my_array)
print("median:")
print(np.median(my_array, axis = 1))
print(np.median(my_array, axis = 0))

[[11 18 16  1 11]
 [ 1  4  7 13 17]
 [17 10  9 19  6]]
median:
[11.  7. 10.]
[11. 10.  9. 13. 11.]


In [6]:
# The max() function returns the maximum value from the array, while the
# min() function returns the minimum value.
# The following script returns the minimum value in a NumPy array using the
# min() method.

my_array = np.array([2,4,8,10,12])
print(my_array)
print("min value:")
print(np.amin(my_array))

[ 2  4  8 10 12]
min value:
2
